name: CraftingNBT
main: io.github.silicondev.craftingnbt.CraftingNBT
version: 0.1
api-version: 1.15
commands:
  cnbt:
    description: The base command for CraftingNBT.
    usage: /cnbt
  cnbt test:
    description: Tests if the plugin is functioning.
    usage: /cnbt test
  cnbt add:
    description: Adds an NBT record.
    usage: /cnbt add <id> <datapack tag> <nbt>
  cnbt remove:
    description: Removes an NBT record.
    usage: /cnbt remove <id>